version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: .Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/mysql-data:/var/lib/mysql
    environment:
      MYSQL_SATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: root
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /users/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge  