version: '3.8'

services:
    mysql:
        image: mysql:8.2.0
        container_name: conference-room
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: myConferencRoom
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
